name: Black Linter

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint
        uses: lgeiger/black-action@master
        with:
          args: "src --check"
