name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.3
        env:
          POSTGRES_DB: db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run Tests
        run: python manage.py test
        env:
          DB_NAME: db
          DB_USER: admin
          DB_PASSWORD: admin
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
